name: Test build srpm
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Tools
        run: dnf -y install rpkg wget
      - name: Build SRPM
        run: |
          bin_version=$(awk -F':' '/^Version/ {gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2}' tsshd.spec)
          wget -q https://github.com/trzsz/tsshd/archive/refs/tags/v${bin_version}.tar.gz
          mkdir -p build
          cp *.spec build/
          rpkg srpm --outdir ./build
      - name: Show Checksum
        run: sha256sum ./build/*.src.rpm
